In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\santosh nandam\Downloads\50_startups.csv")
df.head()

R&D Spend  Administration  Marketing Spend        City     Profit
0  165349.20       136897.80        471784.10     Chennai  192261.83
1  162597.70       151377.59        443898.53     Madurai  191792.06
2  153441.51       101145.55        407934.54  Coimbatore  191050.39
3  144372.41       118671.85        383199.62     Chennai  182901.99
4  142107.34        91391.77        366168.42  Coimbatore  166187.94

In [3]:
df.shape

(50, 5)

In [4]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
City               0
Profit             0
dtype: int64

In [5]:
x =df.iloc[:,:-1].values
y= df.iloc[:,4].values
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
le_x = LabelEncoder()
x[:,3] = le_x.fit_transform(x[:,3])
ohe_x = ColumnTransformer([('one_hot_encoder', OneHotEncoder(),[3])],remainder = 'passthrough')
x = np.array(ohe_x.fit_transform(x), dtype =int)

In [7]:
x

array([[     1,      0,      0, 165349, 136897, 471784],
       [     0,      0,      1, 162597, 151377, 443898],
       [     0,      1,      0, 153441, 101145, 407934],
       [     1,      0,      0, 144372, 118671, 383199],
       [     0,      1,      0, 142107,  91391, 366168],
       [     1,      0,      0, 131876,  99814, 362861],
       [     0,      0,      1, 134615, 147198, 127716],
       [     0,      1,      0, 130298, 145530, 323876],
       [     1,      0,      0, 120542, 148718, 311613],
       [     0,      0,      1, 123334, 108679, 304981],
       [     0,      1,      0, 101913, 110594, 229160],
       [     0,      0,      1, 100671,  91790, 249744],
       [     0,      1,      0,  93863, 127320, 249839],
       [     0,      0,      1,  91992, 135495, 252664],
       [     0,      1,      0, 119943, 156547, 256512],
       [     1,      0,      0, 114523, 122616, 261776],
       [     0,      0,      1,  78013, 121597, 264346],
       [     1,      0,      0,

In [8]:
x=x[:,1:]

In [9]:
x

array([[     0,      0, 165349, 136897, 471784],
       [     0,      1, 162597, 151377, 443898],
       [     1,      0, 153441, 101145, 407934],
       [     0,      0, 144372, 118671, 383199],
       [     1,      0, 142107,  91391, 366168],
       [     0,      0, 131876,  99814, 362861],
       [     0,      1, 134615, 147198, 127716],
       [     1,      0, 130298, 145530, 323876],
       [     0,      0, 120542, 148718, 311613],
       [     0,      1, 123334, 108679, 304981],
       [     1,      0, 101913, 110594, 229160],
       [     0,      1, 100671,  91790, 249744],
       [     1,      0,  93863, 127320, 249839],
       [     0,      1,  91992, 135495, 252664],
       [     1,      0, 119943, 156547, 256512],
       [     0,      0, 114523, 122616, 261776],
       [     0,      1,  78013, 121597, 264346],
       [     0,      0,  94657, 145077, 282574],
       [     1,      0,  91749, 114175, 294919],
       [     0,      0,  86419, 153514,      0],
       [     0,     

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=.30,random_state = 0)

In [11]:
from sklearn.linear_model import LinearRegression
regress=LinearRegression()
regress.fit(x_train,y_train)

LinearRegression()

In [12]:
y_pred=regress.predict(x_test)
y_pred

array([104282.74845357, 132536.53849928, 133911.11921423,  72584.35572911,
       179920.88369287, 114549.21392778,  66444.25735029,  98404.98885339,
       114499.7731262 , 169367.57489704,  96522.21039595,  88040.95894935,
       110949.65365898,  90419.61586831, 128020.69204363])

In [13]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94,  96778.92,  96479.51,
       105733.54,  96712.8 , 124266.9 ])

In [14]:
regress.score(x_train,y_train)

0.9515563254725671

In [15]:
regress.score(x_test,y_test)

0.9358682078683229

In [16]:
import statsmodels.api as sm

In [17]:
x=np.append(arr=np.ones(shape=(50,1),dtype=int),values=x,axis=1)

In [18]:
x

array([[     1,      0,      0, 165349, 136897, 471784],
       [     1,      0,      1, 162597, 151377, 443898],
       [     1,      1,      0, 153441, 101145, 407934],
       [     1,      0,      0, 144372, 118671, 383199],
       [     1,      1,      0, 142107,  91391, 366168],
       [     1,      0,      0, 131876,  99814, 362861],
       [     1,      0,      1, 134615, 147198, 127716],
       [     1,      1,      0, 130298, 145530, 323876],
       [     1,      0,      0, 120542, 148718, 311613],
       [     1,      0,      1, 123334, 108679, 304981],
       [     1,      1,      0, 101913, 110594, 229160],
       [     1,      0,      1, 100671,  91790, 249744],
       [     1,      1,      0,  93863, 127320, 249839],
       [     1,      0,      1,  91992, 135495, 252664],
       [     1,      1,      0, 119943, 156547, 256512],
       [     1,      0,      0, 114523, 122616, 261776],
       [     1,      0,      1,  78013, 121597, 264346],
       [     1,      0,      0,

In [19]:
x_ov=x[:,[0,1,2,3,4,5]]
regress_ols=sm.OLS(endog=y,exog=x_ov).fit()
regress_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Wed, 12 Mar 2025   Prob (F-statistic):           1.34e-27
Time:                        17:22:35   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.008e+04   6952.617      7.204      0.000    3.61e+04    6.41e+04
x1           240.7605   3338.877      0.072      0.943   -6488.304    6969.825
x2            42.0063   3256.058      0.013      0.990   -6520.148    6604.161
x3             0.8060      0.046     17.368      0.000       0.712       0.900
x4            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x5             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.783   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.267
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.47e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.47e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [20]:
x_ov

array([[     1,      0,      0, 165349, 136897, 471784],
       [     1,      0,      1, 162597, 151377, 443898],
       [     1,      1,      0, 153441, 101145, 407934],
       [     1,      0,      0, 144372, 118671, 383199],
       [     1,      1,      0, 142107,  91391, 366168],
       [     1,      0,      0, 131876,  99814, 362861],
       [     1,      0,      1, 134615, 147198, 127716],
       [     1,      1,      0, 130298, 145530, 323876],
       [     1,      0,      0, 120542, 148718, 311613],
       [     1,      0,      1, 123334, 108679, 304981],
       [     1,      1,      0, 101913, 110594, 229160],
       [     1,      0,      1, 100671,  91790, 249744],
       [     1,      1,      0,  93863, 127320, 249839],
       [     1,      0,      1,  91992, 135495, 252664],
       [     1,      1,      0, 119943, 156547, 256512],
       [     1,      0,      0, 114523, 122616, 261776],
       [     1,      0,      1,  78013, 121597, 264346],
       [     1,      0,      0,

In [21]:
x_ovc=x_ov[:,1:]

In [22]:
from sklearn.model_selection import train_test_split
x_ov_train,x_ov_test,y_ov_train,y_ov_test=train_test_split(x_ov,y,test_size=.30, random_state=0)

In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
regress_ov1=LinearRegression()
regress_ov1.fit(x_ov_train,y_ov_train)

LinearRegression()

In [25]:
regress_ov1.score(x_ov_train,y_ov_train)

0.9515563254725671

In [26]:
regress_ov1.score(x_ov_test,y_ov_test)

0.9358682078683059

In [27]:
x_ov=x[:,[0,1,3,4,5]]
regress_ols=sm.OLS(endog=y,exog=x_ov).fit()
regress_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Wed, 12 Mar 2025   Prob (F-statistic):           8.49e-29
Time:                        17:22:35   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.011e+04   6647.901      7.537      0.000    3.67e+04    6.35e+04
x1           220.1847   2900.553      0.076      0.940   -5621.828    6062.198
x2             0.8060      0.046     17.606      0.000       0.714       0.898
x3            -0.0270      0.052     -0.523      0.604      -0.131       0.077
x4             0.0270      0.017      1.592      0.118      -0.007       0.061
==============================================================================
Omnibus:                       14.759   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.173
Skew:                          -0.948   Prob(JB):                     2.53e-05
Kurtosis:                       5.563   Cond. No.                     1.40e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [28]:
x_ovc=x_ov[:,1:]
x_ov_train,x_ov_test,y_ov_train,y_ov_test=train_test_split(x_ov,y,test_size=.30,random_state=0)

In [29]:
from sklearn.linear_model import LinearRegression
regress_ov2=LinearRegression()
regress_ov2.fit(x_ov_train,y_ov_train)

LinearRegression()

In [30]:
regress_ov2.score(x_ov_train,y_ov_train)

0.9515467487890941

In [31]:
regress_ov2.score(x_ov_test,y_ov_test)

0.9358854142063172

In [32]:
x_ov = x[:,[0,3,4,5]]
regress_ols = sm.OLS(endog=y, exog = x_ov).fit()
regress_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Wed, 12 Mar 2025   Prob (F-statistic):           4.53e-30
Time:                        17:22:35   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.384      7.626      0.000    3.69e+04    6.34e+04
x1             0.8057      0.045     17.846      0.000       0.715       0.897
x2            -0.0268      0.051     -0.526      0.602      -0.130       0.076
x3             0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.839   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.443
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.587   Cond. No.                     1.40e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [33]:
x_ovc = x_ov[:,1:]
x_ov_train,x_ov_test,y_ov_train,y_ov_test=train_test_split(x_ov,y,test_size=.30,random_state=0)

In [34]:
from sklearn.linear_model import LinearRegression
regress_ov3 = LinearRegression()
regress_ov3.fit(x_ov_train, y_ov_train)

LinearRegression()

In [35]:
regress_ov3.score(x_ov_train, y_ov_train)

0.9515383544673244

In [36]:
regress_ov3.score(x_ov_test, y_ov_test)

0.9355189542547091

In [37]:
x_ov

array([[     1, 165349, 136897, 471784],
       [     1, 162597, 151377, 443898],
       [     1, 153441, 101145, 407934],
       [     1, 144372, 118671, 383199],
       [     1, 142107,  91391, 366168],
       [     1, 131876,  99814, 362861],
       [     1, 134615, 147198, 127716],
       [     1, 130298, 145530, 323876],
       [     1, 120542, 148718, 311613],
       [     1, 123334, 108679, 304981],
       [     1, 101913, 110594, 229160],
       [     1, 100671,  91790, 249744],
       [     1,  93863, 127320, 249839],
       [     1,  91992, 135495, 252664],
       [     1, 119943, 156547, 256512],
       [     1, 114523, 122616, 261776],
       [     1,  78013, 121597, 264346],
       [     1,  94657, 145077, 282574],
       [     1,  91749, 114175, 294919],
       [     1,  86419, 153514,      0],
       [     1,  76253, 113867, 298664],
       [     1,  78389, 153773, 299737],
       [     1,  73994, 122782, 303319],
       [     1,  67532, 105751, 304768],
       [     1, 

In [38]:
x_ov=x[:,[0,3,5]]
regress_ols = sm.OLS(endog=y, exog = x_ov).fit()
regress_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Wed, 12 Mar 2025   Prob (F-statistic):           2.16e-31
Time:                        17:22:35   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.941     17.464      0.000    4.16e+04    5.24e+04
x1             0.7966      0.041     19.265      0.000       0.713       0.880
x2             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.678   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.162
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [39]:
x_ovc=x_ov[:,1:]
x_ov_train,x_ov_test,y_ov_train,y_ov_test=train_test_split(x_ov,y,test_size=.30,random_state=0)

In [40]:
from sklearn.linear_model import LinearRegression
regress_ov4=LinearRegression()
regress_ov4.fit(x_ov_train,y_ov_train)

LinearRegression()

In [41]:
regress_ov4.score(x_ov_train,y_ov_train)

0.9512556961080694

In [42]:
regress_ov4.score(x_ov_test,y_ov_test)

0.9431309583591085

In [43]:
x_ov = x[:,[0,3]]
regress_ols = sm.OLS(endog=y, exog = x_ov).fit()
regress_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Wed, 12 Mar 2025   Prob (F-statistic):           3.50e-32
Time:                        17:22:36   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.900     19.320      0.000    4.39e+04    5.41e+04
x1             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.538
Skew:                          -0.911   Prob(JB):                     9.43e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [44]:
x_ovc=x_ov[:,1:]
x_ov_train,x_ov_test,y_ov_train,y_ov_test=train_test_split(x_ov,y,test_size=.30,random_state=0)

In [45]:
from sklearn.linear_model import LinearRegression
regress_ov5 = LinearRegression()
regress_ov5.fit(x_ov_train, y_ov_train)

LinearRegression()

In [46]:
regress_ov5.score(x_ov_train, y_ov_train)

0.9476436934242192

In [47]:
regress_ov5.score(x_ov_test, y_ov_test)

0.9360403445633265